### ISSUE TITLE
Project doesn't include a license

### ISSUE THREAD

**Issue by lextoumbourou** [borntyping/python-csdl#2]
Hi there,

Thanks a lot for putting this code together! :smile:

I noticed that this repo doesn't include a license. Is there any reason for that?

**Comment by borntyping** [comment]
Other than the project being very quickly put together for hackday, no :)

I'll add one and update the README when I have a moment.

**Comment by borntyping** [comment]
Fixed by https://github.com/borntyping/python-csdl/pull/3 :)
